[2024-11-26T09:09:32.542+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-26T09:09:32.564+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_pipeline.process_and_load_data manual__2024-11-26T09:04:12.655901+00:00 [queued]>
[2024-11-26T09:09:32.570+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_pipeline.process_and_load_data manual__2024-11-26T09:04:12.655901+00:00 [queued]>
[2024-11-26T09:09:32.571+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2024-11-26T09:09:32.581+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_and_load_data> on 2024-11-26 09:04:12.655901+00:00
[2024-11-26T09:09:32.591+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'amazon_pipeline', 'process_and_load_data', 'manual__2024-11-26T09:04:12.655901+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/amazon_pipeline_dag.py', '--cfg-path', '/tmp/tmpp6fobj9e']
[2024-11-26T09:09:32.593+0000] {standard_task_runner.py:91} INFO - Job 41: Subtask process_and_load_data
[2024-11-26T09:09:32.594+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3505) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-26T09:09:32.594+0000] {standard_task_runner.py:63} INFO - Started process 3531 to run task
[2024-11-26T09:09:32.630+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_pipeline.process_and_load_data manual__2024-11-26T09:04:12.655901+00:00 [running]> on host d62e07581dba
[2024-11-26T09:09:32.687+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_pipeline' AIRFLOW_CTX_TASK_ID='process_and_load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T09:04:12.655901+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-26T09:04:12.655901+00:00'
[2024-11-26T09:09:32.688+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-26T09:09:32.805+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-26T09:09:32.806+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/spark_milvus_task.py", line 16, in process_and_insert_data
    spark = SparkSession.builder.appName("AmazonDataPipeline").getOrCreate()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-11-26T09:09:32.814+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=amazon_pipeline, task_id=process_and_load_data, run_id=manual__2024-11-26T09:04:12.655901+00:00, execution_date=20241126T090412, start_date=20241126T090932, end_date=20241126T090932
[2024-11-26T09:09:32.823+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 41 for task process_and_load_data ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 3531)
[2024-11-26T09:09:32.848+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-26T09:09:32.859+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-26T09:09:32.861+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
