[2024-11-27T04:18:31.307+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-27T04:18:31.330+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_recommendation_pipeline_elt.transform_data manual__2024-11-27T04:18:13.071416+00:00 [queued]>
[2024-11-27T04:18:31.337+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_recommendation_pipeline_elt.transform_data manual__2024-11-27T04:18:13.071416+00:00 [queued]>
[2024-11-27T04:18:31.337+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-11-27T04:18:31.347+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2024-11-27 04:18:13.071416+00:00
[2024-11-27T04:18:31.355+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'amazon_recommendation_pipeline_elt', 'transform_data', 'manual__2024-11-27T04:18:13.071416+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/amazon_recommendation_dag.py', '--cfg-path', '/tmp/tmpb5tgeaq5']
[2024-11-27T04:18:31.357+0000] {standard_task_runner.py:91} INFO - Job 99: Subtask transform_data
[2024-11-27T04:18:31.358+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=11421) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-27T04:18:31.358+0000] {standard_task_runner.py:63} INFO - Started process 11433 to run task
[2024-11-27T04:18:31.392+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_recommendation_pipeline_elt.transform_data manual__2024-11-27T04:18:13.071416+00:00 [running]> on host bece637e0b85
[2024-11-27T04:18:31.457+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_recommendation_pipeline_elt' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T04:18:13.071416+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-27T04:18:13.071416+00:00'
[2024-11-27T04:18:31.459+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-27T04:18:31.459+0000] {spark_transform_task.py:32} INFO - Using processed file path: None
[2024-11-27T04:18:31.460+0000] {spark_transform_task.py:35} INFO - Initializing Spark session...
[2024-11-27T04:18:34.055+0000] {spark_transform_task.py:41} INFO - Spark session initialized successfully.
[2024-11-27T04:18:34.056+0000] {spark_transform_task.py:44} INFO - Loading data from None...
[2024-11-27T04:18:34.890+0000] {spark_transform_task.py:68} ERROR - An error occurred during data transformation: [PATH_NOT_FOUND] Path does not exist: file:/opt/***/None.
[2024-11-27T04:18:34.891+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-27T04:18:34.891+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/spark_transform_task.py", line 45, in transform_data
    df = spark.read.json(processed_file_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 418, in json
    return self._df(self._jreader.json(self._spark._sc._jvm.PythonUtils.toSeq(path)))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/errors/exceptions/captured.py", line 175, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/opt/airflow/None.
[2024-11-27T04:18:34.906+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=amazon_recommendation_pipeline_elt, task_id=transform_data, run_id=manual__2024-11-27T04:18:13.071416+00:00, execution_date=20241127T041813, start_date=20241127T041831, end_date=20241127T041834
[2024-11-27T04:18:34.919+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 99 for task transform_data ([PATH_NOT_FOUND] Path does not exist: file:/opt/airflow/None.; 11433)
[2024-11-27T04:18:34.944+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-27T04:18:34.958+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-27T04:18:34.960+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
