[2024-11-27T04:06:58.592+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-27T04:06:58.616+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_recommendation_pipeline.transform_data manual__2024-11-27T04:01:43.565457+00:00 [queued]>
[2024-11-27T04:06:58.622+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_recommendation_pipeline.transform_data manual__2024-11-27T04:01:43.565457+00:00 [queued]>
[2024-11-27T04:06:58.623+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2024-11-27T04:06:58.631+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2024-11-27 04:01:43.565457+00:00
[2024-11-27T04:06:58.638+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'amazon_recommendation_pipeline', 'transform_data', 'manual__2024-11-27T04:01:43.565457+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/amazon_recommendation_dag.py', '--cfg-path', '/tmp/tmpf_6e_0ei']
[2024-11-27T04:06:58.640+0000] {standard_task_runner.py:91} INFO - Job 89: Subtask transform_data
[2024-11-27T04:06:58.641+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4652) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-27T04:06:58.642+0000] {standard_task_runner.py:63} INFO - Started process 4654 to run task
[2024-11-27T04:06:58.676+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_recommendation_pipeline.transform_data manual__2024-11-27T04:01:43.565457+00:00 [running]> on host bece637e0b85
[2024-11-27T04:06:58.741+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_recommendation_pipeline' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T04:01:43.565457+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-27T04:01:43.565457+00:00'
[2024-11-27T04:06:58.743+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-27T04:06:58.743+0000] {spark_transform_task.py:33} INFO - Using RAW_DATA_PATH: /opt/***/dags/tasks/raw_data_20241127_040148.json
[2024-11-27T04:06:58.744+0000] {spark_transform_task.py:34} INFO - Using PROCESSED_DATA_PATH: /opt/***/dags/tasks
[2024-11-27T04:06:58.745+0000] {spark_transform_task.py:43} INFO - Ensured processed data path exists: /opt/***/dags/tasks
[2024-11-27T04:06:58.746+0000] {spark_transform_task.py:46} INFO - Initializing Spark session...
[2024-11-27T04:07:01.337+0000] {spark_transform_task.py:52} INFO - Spark session initialized successfully.
[2024-11-27T04:07:01.338+0000] {spark_transform_task.py:55} INFO - Loading raw data from /opt/***/dags/tasks/raw_data_20241127_040148.json...
[2024-11-27T04:07:04.408+0000] {spark_transform_task.py:57} INFO - Raw data loaded into Spark DataFrame with 170 rows.
[2024-11-27T04:07:04.409+0000] {spark_transform_task.py:60} INFO - Schema of loaded DataFrame:
[2024-11-27T04:07:04.410+0000] {logging_mixin.py:188} INFO - root
 |-- _corrupt_record: string (nullable = true)
[2024-11-27T04:07:04.441+0000] {spark_transform_task.py:68} ERROR - Column 'price' not found in raw data!
[2024-11-27T04:07:04.442+0000] {spark_transform_task.py:90} ERROR - An error occurred during data transformation: Column 'price' not found in raw data!
[2024-11-27T04:07:04.442+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-27T04:07:04.442+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/spark_transform_task.py", line 69, in transform_data
    raise ValueError("Column 'price' not found in raw data!")
ValueError: Column 'price' not found in raw data!
[2024-11-27T04:07:04.449+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=amazon_recommendation_pipeline, task_id=transform_data, run_id=manual__2024-11-27T04:01:43.565457+00:00, execution_date=20241127T040143, start_date=20241127T040658, end_date=20241127T040704
[2024-11-27T04:07:04.460+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 89 for task transform_data (Column 'price' not found in raw data!; 4654)
[2024-11-27T04:07:04.489+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-27T04:07:04.509+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-27T04:07:04.511+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
