[2024-11-26T09:01:29.751+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-26T09:01:29.792+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_pipeline.process_and_load_data manual__2024-11-26T09:01:19.093283+00:00 [queued]>
[2024-11-26T09:01:29.799+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_pipeline.process_and_load_data manual__2024-11-26T09:01:19.093283+00:00 [queued]>
[2024-11-26T09:01:29.800+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-11-26T09:01:29.810+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_and_load_data> on 2024-11-26 09:01:19.093283+00:00
[2024-11-26T09:01:29.820+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'amazon_pipeline', 'process_and_load_data', 'manual__2024-11-26T09:01:19.093283+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/amazon_pipeline_dag.py', '--cfg-path', '/tmp/tmpsrj10gh5']
[2024-11-26T09:01:29.822+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask process_and_load_data
[2024-11-26T09:01:29.824+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=7345) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-26T09:01:29.824+0000] {standard_task_runner.py:63} INFO - Started process 7358 to run task
[2024-11-26T09:01:29.862+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_pipeline.process_and_load_data manual__2024-11-26T09:01:19.093283+00:00 [running]> on host ca7d491041e1
[2024-11-26T09:01:29.926+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_pipeline' AIRFLOW_CTX_TASK_ID='process_and_load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T09:01:19.093283+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-26T09:01:19.093283+00:00'
[2024-11-26T09:01:29.928+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-26T09:01:30.046+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-26T09:01:30.046+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/spark_milvus_task.py", line 16, in process_and_insert_data
    spark = SparkSession.builder.appName("AmazonDataPipeline").getOrCreate()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-11-26T09:01:30.054+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=amazon_pipeline, task_id=process_and_load_data, run_id=manual__2024-11-26T09:01:19.093283+00:00, execution_date=20241126T090119, start_date=20241126T090129, end_date=20241126T090130
[2024-11-26T09:01:30.064+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 28 for task process_and_load_data ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 7358)
[2024-11-26T09:01:30.078+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-26T09:01:30.091+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-26T09:01:30.093+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
