[2024-11-27T04:19:53.357+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-27T04:19:53.378+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_recommendation_pipeline_elt.transform_data scheduled__2024-11-26T00:00:00+00:00 [queued]>
[2024-11-27T04:19:53.383+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_recommendation_pipeline_elt.transform_data scheduled__2024-11-26T00:00:00+00:00 [queued]>
[2024-11-27T04:19:53.383+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-11-27T04:19:53.392+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2024-11-26 00:00:00+00:00
[2024-11-27T04:19:53.402+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'amazon_recommendation_pipeline_elt', 'transform_data', 'scheduled__2024-11-26T00:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/amazon_recommendation_dag.py', '--cfg-path', '/tmp/tmpv3bq408e']
[2024-11-27T04:19:53.403+0000] {standard_task_runner.py:91} INFO - Job 102: Subtask transform_data
[2024-11-27T04:19:53.404+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=12333) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-27T04:19:53.404+0000] {standard_task_runner.py:63} INFO - Started process 12336 to run task
[2024-11-27T04:19:53.436+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_recommendation_pipeline_elt.transform_data scheduled__2024-11-26T00:00:00+00:00 [running]> on host bece637e0b85
[2024-11-27T04:19:53.494+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_recommendation_pipeline_elt' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-26T00:00:00+00:00'
[2024-11-27T04:19:53.495+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-27T04:19:53.496+0000] {spark_transform_task.py:32} INFO - Using processed file path: None
[2024-11-27T04:19:53.496+0000] {spark_transform_task.py:36} ERROR - Processed file path does not exist: None
[2024-11-27T04:19:53.497+0000] {spark_transform_task.py:73} ERROR - File not found: Processed file not found: None
[2024-11-27T04:19:53.497+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-27T04:19:53.497+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/spark_transform_task.py", line 37, in transform_data
    raise FileNotFoundError(f"Processed file not found: {processed_file_path}")
FileNotFoundError: Processed file not found: None
[2024-11-27T04:19:53.508+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=amazon_recommendation_pipeline_elt, task_id=transform_data, run_id=scheduled__2024-11-26T00:00:00+00:00, execution_date=20241126T000000, start_date=20241127T041953, end_date=20241127T041953
[2024-11-27T04:19:53.519+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 102 for task transform_data (Processed file not found: None; 12336)
[2024-11-27T04:19:53.538+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-27T04:19:53.550+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-27T04:19:53.552+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
