[2024-11-27T04:04:30.609+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-27T04:04:30.629+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_recommendation_pipeline.transform_data manual__2024-11-27T04:04:24.388587+00:00 [queued]>
[2024-11-27T04:04:30.635+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_recommendation_pipeline.transform_data manual__2024-11-27T04:04:24.388587+00:00 [queued]>
[2024-11-27T04:04:30.636+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-11-27T04:04:30.646+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2024-11-27 04:04:24.388587+00:00
[2024-11-27T04:04:30.653+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'amazon_recommendation_pipeline', 'transform_data', 'manual__2024-11-27T04:04:24.388587+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/amazon_recommendation_dag.py', '--cfg-path', '/tmp/tmpuh7i33zx']
[2024-11-27T04:04:30.655+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2960) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-27T04:04:30.664+0000] {standard_task_runner.py:91} INFO - Job 86: Subtask transform_data
[2024-11-27T04:04:30.664+0000] {standard_task_runner.py:63} INFO - Started process 2962 to run task
[2024-11-27T04:04:30.704+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_recommendation_pipeline.transform_data manual__2024-11-27T04:04:24.388587+00:00 [running]> on host bece637e0b85
[2024-11-27T04:04:30.770+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_recommendation_pipeline' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T04:04:24.388587+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-27T04:04:24.388587+00:00'
[2024-11-27T04:04:30.772+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-27T04:04:30.773+0000] {spark_transform_task.py:33} INFO - Using RAW_DATA_PATH: /opt/***/dags/tasks/raw_data_20241127_040429.json
[2024-11-27T04:04:30.773+0000] {spark_transform_task.py:34} INFO - Using PROCESSED_DATA_PATH: /opt/***/dags/tasks
[2024-11-27T04:04:30.774+0000] {spark_transform_task.py:38} INFO - Ensured processed data path exists: /opt/***/dags/tasks
[2024-11-27T04:04:30.775+0000] {spark_transform_task.py:41} INFO - Initializing Spark session...
[2024-11-27T04:04:32.810+0000] {spark_transform_task.py:47} INFO - Spark session initialized successfully.
[2024-11-27T04:04:32.810+0000] {spark_transform_task.py:50} INFO - Loading raw data from /opt/***/dags/tasks/raw_data_20241127_040429.json...
[2024-11-27T04:04:36.321+0000] {spark_transform_task.py:52} INFO - Raw data loaded into Spark DataFrame with 226 rows.
[2024-11-27T04:04:36.321+0000] {spark_transform_task.py:55} INFO - Schema of loaded DataFrame:
[2024-11-27T04:04:36.323+0000] {logging_mixin.py:188} INFO - root
 |-- _corrupt_record: string (nullable = true)
[2024-11-27T04:04:36.365+0000] {spark_transform_task.py:63} ERROR - Column 'price' not found in raw data!
[2024-11-27T04:04:36.366+0000] {spark_transform_task.py:85} ERROR - An error occurred during data transformation: Column 'price' not found in raw data!
[2024-11-27T04:04:36.367+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-27T04:04:36.368+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/spark_transform_task.py", line 64, in transform_data
    raise ValueError("Column 'price' not found in raw data!")
ValueError: Column 'price' not found in raw data!
[2024-11-27T04:04:36.379+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=amazon_recommendation_pipeline, task_id=transform_data, run_id=manual__2024-11-27T04:04:24.388587+00:00, execution_date=20241127T040424, start_date=20241127T040430, end_date=20241127T040436
[2024-11-27T04:04:36.392+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 86 for task transform_data (Column 'price' not found in raw data!; 2962)
[2024-11-27T04:04:36.410+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-27T04:04:36.433+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-27T04:04:36.436+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
