[2024-11-27T04:03:36.350+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-27T04:03:36.375+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_recommendation_pipeline.transform_data manual__2024-11-27T04:03:29.936937+00:00 [queued]>
[2024-11-27T04:03:36.383+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_recommendation_pipeline.transform_data manual__2024-11-27T04:03:29.936937+00:00 [queued]>
[2024-11-27T04:03:36.384+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-11-27T04:03:36.394+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2024-11-27 04:03:29.936937+00:00
[2024-11-27T04:03:36.402+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'amazon_recommendation_pipeline', 'transform_data', 'manual__2024-11-27T04:03:29.936937+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/amazon_recommendation_dag.py', '--cfg-path', '/tmp/tmp6kmmu8x9']
[2024-11-27T04:03:36.403+0000] {standard_task_runner.py:91} INFO - Job 83: Subtask transform_data
[2024-11-27T04:03:36.405+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2415) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-27T04:03:36.406+0000] {standard_task_runner.py:63} INFO - Started process 2418 to run task
[2024-11-27T04:03:36.438+0000] {task_command.py:426} INFO - Running <TaskInstance: amazon_recommendation_pipeline.transform_data manual__2024-11-27T04:03:29.936937+00:00 [running]> on host bece637e0b85
[2024-11-27T04:03:36.503+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_recommendation_pipeline' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T04:03:29.936937+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-27T04:03:29.936937+00:00'
[2024-11-27T04:03:36.505+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-27T04:03:36.506+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-27T04:03:36.506+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/tasks/spark_transform_task.py", line 13, in transform_data
    logger.info(f"Using RAW_DATA_PATH: {raw_file_path}")
    ^^^^^^
NameError: name 'logger' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/spark_transform_task.py", line 65, in transform_data
    logger.error(f"An error occurred during data transformation: {str(e)}")
    ^^^^^^
NameError: name 'logger' is not defined
[2024-11-27T04:03:36.519+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=amazon_recommendation_pipeline, task_id=transform_data, run_id=manual__2024-11-27T04:03:29.936937+00:00, execution_date=20241127T040329, start_date=20241127T040336, end_date=20241127T040336
[2024-11-27T04:03:36.529+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 83 for task transform_data (name 'logger' is not defined; 2418)
[2024-11-27T04:03:36.539+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-27T04:03:36.553+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-27T04:03:36.555+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
